### ISSUE TITLE
Platform compatibility

### ISSUE THREAD

**Issue by caffeine-addictt** [caffeine-addictt/template#23]
The setup script was developed for and on Linux.

Might not be compatible with other OSes. PRs welcome.

## Spec

- [ ] Porting bash to node

**Comment by LyubomirT** [comment]
It's good to see you again @caffeine-addictt! I'm not a master of Bash, but may I try to optimize it for Windows (Sadly I don't have a Mac so Windows is the best thing I can do for now)?

**Comment by caffeine-addictt** [comment]
Sure thing @LyubomirT :>

However as `setup.sh` is running UNIX commands, I doubt it will run on cmd or powershell, it should run fine on WSL though. Also considering windows uses `\` for path and UNIX uses `/` for path, there may be some conflicts. It might be best to make a separate `win_setup.sh` script.

What do you think?

**Comment by LyubomirT** [comment]
Perhaps that'll be the best course of action (and the most popular one among developers, too), I think it'd be a great way to do that. Although we might want to create something that does the same but is written in an entirely different language (for example, C#/Python3/Node.js), because languages like those often support many platforms from the start.

**Comment by caffeine-addictt** [comment]
I agree. 

Since formatting is already done with node, it may be best to go with it.
Although the issue now lies in getting js/ts to delete itself.

I'll do some research in the meantime.

**Comment by caffeine-addictt** [comment]
I guess we could still have shell files that run js and handle pre installation and post cleanup.

```text
template/
|_ scripts/
|  |_ main.ts
|_ setup.sh
|_ ...
```

Something like:

```sh
# Check for npm binary
# Invoke npm i

# Run js/ts

# Delete js/ts
# Delete artifacts (node_modules, package.json, etc.)
# Delete itself
```

Likely would need:
- .sh (bash) `UNIX`
- .bat (cmd) `Windows`
- .ps (invokes cmd with .bat)

**Comment by LyubomirT** [comment]
> I guess we could still have shell files that run js and handle pre installation and post cleanup.
> 
> ```
> ...
> ```
> 
> Something like:
> 
> ```shell
> ...
> ```
> 
> Likely would need:
> 
> * .sh (bash) `UNIX`
> * .bat (cmd) `Windows`
> * .ps (invokes cmd with .bat)

Good idea! I think we could also skip the artifacts / npm part completely (will require less setup from the side of the user) if we manage to write the setup script with 0 dependencies and put it in a GitHub repository or any other accessible source.

**Comment by caffeine-addictt** [comment]
In that case, how about having users copy scripts directly to the CLI from the README?

```sh
# README

# Linux
chmod +x ./setup.sh && ./setup.sh && rm -rf artifacts
```

**Comment by LyubomirT** [comment]
> In that case, how about having users copy scripts directly to the CLI from the README?
> 
> ```shell
> # README
> 
> # Linux
> chmod +x ./setup.sh && ./setup.sh && rm -rf artifacts
> ```

It could be a bit daunting in my opinion, people prefer when everything's interactive nowadays. Plus, I doubt it'll take long to download a 500B file and go through some steps.

**Comment by caffeine-addictt** [comment]
True.
What do you have in mind for implementing it?

**Comment by LyubomirT** [comment]
> True. What do you have in mind for implementing it?

Not forcing anything, but perhaps we could simply port the already-implemented code from Bash to JS, with platform-specific conditions to keep everything in a single script?

**Comment by caffeine-addictt** [comment]
Sounds like a plan.

**Comment by LyubomirT** [comment]
> Sounds like a plan.

Okay then! Starting to work on this issue right away.

**Comment by caffeine-addictt** [comment]
> > Sounds like a plan.
> 
> Okay then! Starting to work on this issue right away.

Running with typescript?

**Comment by LyubomirT** [comment]
> > > Sounds like a plan.
> > 
> > 
> > Okay then! Starting to work on this issue right away.
> 
> Running with typescript?

Perhaps basic Node will do better in this case, as we're aiming for a broader audience, and Node.js is easier to set up for most.
